#!/usr/bin/env bash

POSTGRESQL_DESTINATION="$CURRENT_SUBVOL/postgresql"

BACKUP_POSTGRESQL_USER=${BACKUP_POSTGRESQL_USER:-postgres}

BACKUP_POSTGRESQL_PASS=${BACKUP_POSTGRESQL_PASS:-}

if [[ ${BACKUP_POSTGRESQL_HOST+defined} = defined ]]; then
    if [ ! -d "$POSTGRESQL_DESTINATION" ]; then
        mkdir -p "$POSTGRESQL_DESTINATION"
    fi

    eval "PG_PASSWORD='$BACKUP_POSTGRESQL_PASS' pg_dumpall --host '$BACKUP_POSTGRESQL_HOST' --user '$BACKUP_POSTGRESQL_USER' > $POSTGRESQL_DESTINATION/all.sql"

else
    rm -rf "$POSTGRESQL_DESTINATION"
fi
